version: '3.8'

services:
  nexus:
    image: sonatype/nexus3:3.61.0
    container_name: nexus 
    restart: always
    volumes:
      - "nexus-data:/sonatype-work"
    expose:
      - 8081
    depends_on:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`nexus.visaroads.com`)"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"

  traefik:
    container_name: traefik
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-public-certificates:/certificates"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.visaroads.com`)"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=joe:$$apr1$$8y0lHbQ1$$X7wATyOnJ4fqoZTGY8UYm1"

volumes:
  traefik-public-certificates:
  nexus-data:
